image: docker:stable
services:
- docker:dind

stages:
- build
- release

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build . --pull -t $IMAGE_TAG
    - docker push $IMAGE_TAG

release:
  stage: release
  script:
    - docker build . --pull -t $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
